### ISSUE TITLE
SyntaxError: Unexpected token O

### ISSUE THREAD

**Issue by hb-github** [anvk/google-stocks#1]
![image](https://cloud.githubusercontent.com/assets/3365548/9961297/5c418b90-5e3d-11e5-8717-1a8b849dee50.png)

I am calling this api from setinterval and passing value to socket.io for realtime, but frequently I am getting this error and app get crashed.

please suggest.

**Comment by anvk** [comment]
it does look like a problem inside of `request.js` rather the library (looking at the stack you provided)

Is it possible to send a code example which fails ?

**Comment by anvk** [comment]
Closing due to inactvity
